### ISSUE TITLE
db migrate error

### ISSUE THREAD

**Issue by ryanjkoehler** [shekibobo/user-to-user-example#1]
I'm getting the following error when running rake db:migrate:

== 20150727195155 CreateMatches: migrating ====================================
-- create_table(:matches)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "matched_users" does not exist
: ALTER TABLE "matches" ADD CONSTRAINT "fk_rails_a7f324f796"
FOREIGN KEY ("matched_user_id")
  REFERENCES "matched_users" ("id")

What should I do? Thanks for the demo!

**Comment by shekibobo** [comment]
Fixed the migration file. Rails' foreign key constraints only seem to work if the relationship name matches the table name. You have to do FKR manually on an association if the table name can't be inferred.

Thanks for the report.
